# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-08-04 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_auto_20160804_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetail',
            name='phone_number',
            field=models.BigIntegerField(null=True),
        ),
    ]
